### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by CianOB** [AdobeDocs/workfront-learn.en#1]
Issue in ./help/manage-work/tasks/understand-work-effort.md

"For more information on Work Effort, see the [Work Effort overview](https://experienceleague.adobe.com/docs/workfront/using/manage-work/tasks/task-information/work-effort.html?lang=en) article." - this is the closing statement, but it doesn't link to the article

**Comment by Chuckm165** [comment]
It now links to the article. Thanks.

**Comment by Chuckm165** [comment]
added link
