### ISSUE TITLE
cutoff images

### ISSUE THREAD

**Issue by Avialmonanay** [AdobeDocs/workfront-learn.en#3]
Issue in ./help/custom-data/calculated-expressions/date-and-time-and-mathematical-expressions.md

issue documentation: https://experienceleague.adobe.com/docs/workfront-learn/tutorials-workfront/custom-data/calculated-expressions/date-and-time-and-mathematical-expressions.html?lang=en

both images in this documentation are cutoff so you cannot see the last examples in the list.

**Comment by betseyw15** [comment]
These images are only showing a fraction of the expressions that you can use. They are meant to show the examples but not all of them. Those can be found in the the documentation article found here: https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/calculated-custom-data/calculated-data-expressions.html?lang=en
