### ISSUE TITLE
This page isn't talking about the correct product.

### ISSUE THREAD

**Issue by sschnoor** [AdobeDocs/workfront-learn.en#4]
Issue in ./help/fusion/2-understand-the-basics/initial-scenario-design-walkthrough.md

Bacon ipsum dolor amet ball tip capicola short ribs venison cupim, pastrami brisket. Brisket ham hock beef ribs rump swine. Leberkas jowl hamburger venison ball tip burgdoggen. Beef ribs sirloin ribeye shoulder chicken kevin. Swine ball tip chislic, fatback jowl bacon ham corned beef turducken frankfurter rump leberkas salami kielbasa sausage. Chislic ribeye bresaola, strip steak leberkas t-bone sirloin rump pig porchetta shoulder.

Beef ribs spare ribs pork loin buffalo, meatball pig boudin chuck picanha cow ham short ribs. Beef ribs swine capicola ham hock pork belly. Boudin ribeye prosciutto andouille swine sirloin tenderloin kevin ground round tail alcatra chuck pork bacon pork loin. T-bone rump flank, turducken tongue landjaeger shoulder salami jowl tri-tip kielbasa chicken strip steak frankfurter. Swine tenderloin cupim frankfurter, chislic shank spare ribs pork chop. Corned beef meatball hamburger ham hock drumstick jerky pork chop brisket.

**Comment by Chuckm165** [comment]
This was a test
