### ISSUE TITLE
Video stops at 5:47 every time

### ISSUE THREAD

**Issue by ktayloradbe** [AdobeDocs/workfront-learn.en#5]
Issue in ./help/manage-work/projects/navigate-the-project-page.md

Reported internally by 
adavidson@adobe.com, validated

The tutorial video on this page stops at 5:47 every time, but it should play to end, total of 6:21.  

https://experienceleague.adobe.com/docs/workfront-learn/tutorials-workfront/manage-work/projects/navigate-the-project-page.html?lang=en

**Comment by Chuckm165** [comment]
@ktayloradbe It looks like this is working. I've played it twice now and it doesn't stop early, it plays all the way through as it should. Please retest this in your environment and let me know if it works for you now.

**Comment by ktayloradbe** [comment]
Hi @Chuckm165 unfortunately it's still pausing at 5:47 for me as of today Dec 14, 2022

**Comment by Chuckm165** [comment]
I asked a colleague of mine to test it and she said it doesn't stop for her either. I recommend you call Support and see if they can troubleshoot the problem for you. Good luck!

**Comment by ktayloradbe** [comment]
Hi @Chuckm165 Please reopen this ticket. I've tested this bug multiple times and seems to be happening full stop at 5:47 on Chrome still (validated again today in incognito 3 times) on Safari it's fine. There's something buggy going on with this video or the implementation that needs to be addressed as this is impacting customers. Please see screen recording

https://user-images.githubusercontent.com/109547744/207741124-381aaffc-73b8-44ff-a971-6743c7cb131b.mov

**Comment by ktayloradbe** [comment]
Hi @Chuckm165 just wanted to let you know this may be caused by a bug we just found... unsure, but we're looking into it: https://jira.corp.adobe.com/browse/UGP-8257

**Comment by Chuckm165** [comment]
Great! Yeah, it has to be a bug somewhere. I was viewing it on Chrome with no problem. 
Do you still want me to reopen this ticket? If so, who should I assign it to?

**Comment by ktayloradbe** [comment]
I think it should be open until the issue is resolved so we don't lose sight of this. Whoever manages this page I would think should own the ticket
