### ISSUE TITLE
Northstar Fashion Exhibition Booth project missing in Fusion exercise files

### ISSUE THREAD

**Issue by vovsiienko** [AdobeDocs/workfront-learn.en#9]
Issue in ./help/fusion/1-welcome-to-workfront-fusion/set-up-your-fusion-exercise-files-walkthrough.md

Workfront Fusion tutorial requires Northstar Fashion Exhibition Booth project, but it is missing in the provided Fusion exercise files

**Comment by Chuckm165** [comment]
The Northstar Fashion Exhibition Booth project is one of the projects in the Workfront test drive account. There are other things in the test drive account that are referenced in the exercises as well.

**Comment by vovsiienko** [comment]
Chuck,

Thank you for the information, but it is not available in our test drive.
Don't know, maybe it was there before, but now we have only projects
related to our company.

Could you please send a copy of this project files, so that I could add it
there to be able to complete the WF Fusion trainings?

Sincerely,
Viktoriia

**Comment by Chuckm165** [comment]
Test drives have a short expiration date and are filled with test data only. If you can see projects related to your company you're probably not in a test drive. You can request a test drive for free from this tutorial: https://experienceleague.adobe.com/docs/workfront-learn/tutorials-workfront/fusion/welcome-to-workfront-fusion/workfront-fusion-overview.html?lang=en.
Go to the section titled "Request a Workfront test drive" and follow the link to the form. You need a test drive to do the Fusion training exercises. The test drive includes more than just projects.
